name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  packages: write

jobs:
  set-constants:
    runs-on: ubuntu-latest
    outputs:
      SAMBA_VERSION: ${{ steps.contants.outputs.SAMBA_VERSION }}
      SAMBA_PKG_VERSION_ARM64: ${{ steps.contants.outputs.SAMBA_PKG_VERSION_ARM64 }}
      SAMBA_PKG_VERSION_X64: ${{ steps.contants.outputs.SAMBA_PKG_VERSION_X64 }}
      KRB5_PKG_VERSION_ARM64: ${{ steps.contants.outputs.KRB5_PKG_VERSION_ARM64 }}
      KRB5_PKG_VERSION_X64: ${{ steps.contants.outputs.KRB5_PKG_VERSION_X64 }}
    env:
      # renovate: datasource=deb depName=samba-ad-dc registryUrl=http://ports.ubuntu.com/ubuntu-ports?release=noble&components=universe&binaryArch=arm64
      SAMBA_PKG_VERSION_ARM64: "2:4.19.5+dfsg-4ubuntu9"
      # renovate: datasource=deb depName=samba-ad-dc registryUrl=https://archive.ubuntu.com/ubuntu?release=noble&components=universe&binaryArch=amd64
      SAMBA_PKG_VERSION_X64: "2:4.19.5+dfsg-4ubuntu9"
      # renovate: datasource=deb depName=krb5-user registryUrl=http://ports.ubuntu.com/ubuntu-ports?release=noble&components=universe&binaryArch=arm64
      KRB5_PKG_VERSION_ARM64: "1.20.1-6ubuntu2"
      # renovate: datasource=deb depName=krb5-user registryUrl=https://archive.ubuntu.com/ubuntu?release=noble&components=universe&binaryArch=amd64
      KRB5_PKG_VERSION_X64: "1.20.1-6ubuntu2"
    steps:
      - id: contants
        run: |
          echo -n "SAMBA_VERSION=" >> $GITHUB_OUTPUT
          echo "${SAMBA_PKG_VERSION_ARM64}" | sed -e 's/[0-9]:\([0-9]\+\.[0-9]\+\.[0-9]\+\)\(\+dfsg-\([0-9]\+\)\)\?\(ubuntu\([0-9]*\)\)\?/\1/g' >> $GITHUB_OUTPUT
          echo "SAMBA_PKG_VERSION_ARM64=${SAMBA_PKG_VERSION_ARM64}" >> $GITHUB_OUTPUT
          echo "SAMBA_PKG_VERSION_X64=${SAMBA_PKG_VERSION_X64}" >> $GITHUB_OUTPUT
          echo "KRB5_PKG_VERSION_ARM64=${KRB5_PKG_VERSION_ARM64}" >> $GITHUB_OUTPUT
          echo "KRB5_PKG_VERSION_X64=${KRB5_PKG_VERSION_X64}" >> $GITHUB_OUTPUT
      - id: result
        run: |
          echo "SAMBA_VERSION: ${{ steps.contants.outputs.SAMBA_VERSION }}"
          echo "SAMBA_PKG_VERSION_ARM64: ${{ steps.contants.outputs.SAMBA_PKG_VERSION_ARM64 }}"
          echo "SAMBA_PKG_VERSION_X64: ${{ steps.contants.outputs.SAMBA_PKG_VERSION_X64 }}"
          echo "KRB5_PKG_VERSION_ARM64: ${{ steps.contants.outputs.KRB5_PKG_VERSION_ARM64 }}"
          echo "KRB5_PKG_VERSION_X64: ${{ steps.contants.outputs.KRB5_PKG_VERSION_X64 }}"

  build:
    runs-on: ubuntu-latest
    needs: set-constants

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
      name: Docker login
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=latest
          type=semver,pattern={{version}},value=${{ needs.set-constants.outputs.SAMBA_VERSION }}
          type=sha,format=long
          type=schedule,pattern={{date 'YYYYMMDD-hhmmss'}}

    - name: Build the Docker image
      uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6
      with:
        context: .
        push: false
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          SAMBA_VERSION_ARM64=${{ needs.set-constants.outputs.SAMBA_PKG_VERSION_ARM64 }}
          SAMBA_VERSION_X64=${{ needs.set-constants.outputs.SAMBA_PKG_VERSION_X64 }}
          KRB5_VERSION_ARM64=${{ needs.set-constants.outputs.KRB5_PKG_VERSION_ARM64 }}
          KRB5_VERSION_X64=${{ needs.set-constants.outputs.KRB5_PKG_VERSION_X64 }}

    - name: Build And Push the Docker image
      uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          SAMBA_VERSION_ARM64=${{ needs.set-constants.outputs.SAMBA_PKG_VERSION_ARM64 }}
          SAMBA_VERSION_X64=${{ needs.set-constants.outputs.SAMBA_PKG_VERSION_X64 }}
          KRB5_VERSION_ARM64=${{ needs.set-constants.outputs.KRB5_PKG_VERSION_ARM64 }}
          KRB5_VERSION_X64=${{ needs.set-constants.outputs.KRB5_PKG_VERSION_X64 }}
